version: "3.8"

services:
  server:
    build:
      context: ./
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '8000:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html:cached
    depends_on:
      - php
      - mysql
  php:
    build:
      context: ./
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:cached
  mysql:
    image: 'mysql:5.7'
    env_file:
      - ./env/mysql.env
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html:cached
  artisan:
    build:
      context: ./
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:cached
    entrypoint: [ "php", "/var/www/html/artisan" ]
  npm:
    image: node:15
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html:cached
    entrypoint: [ "npm" ]