apiVersion: v1
kind: Service
metadata:
  name: second-app-service
  labels:
    group: example
spec:
  selector:
    app: second-app
  ports:
    - port: 80
      protocol: 'TCP'
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
  labels:
    group: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-app
      tier: backend
    # matchExpressions:
    #   - { key: app, operator: In, values: [second-app, first-app] }
  template:
    metadata:
      labels:
        app: second-app
        tier: backend
    spec:
      containers:
        - name: second-node
          image: marchino/kub-first-app:2
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          #   periodSeconds: 10
          #   initialDelaySeconds: 5
          imagePullPolicy: Always
          resources:
              limits:
                memory: 1Gi
                cpu: "1"
