apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: marchino/kub-demo-frontend:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        env:
          - name: USERS_ADDRESS
            value: "users-service.default:8080"
          - name: TASKS_ADDRESS
            value: "tasks-service.default:8000"
