apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  type: LoadBalancer
  selector:
    app: users
  ports:
  - protocol: TCP
    port: 8080 # Public facing
    targetPort: 8080 # Container internal

