apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: marchino/kub-demo-users:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        env:
          - name: AUTH_ADDRESS
            value: "10.100.59.139"
